name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push api-gateway
        uses: docker/build-push-action@v5
        with:
          context: ./Cafe_Management_System/api-gateway
          push: true
          tags: zaimabbasi/cafe-api-gateway:latest

      - name: build and push menu-service
        uses: docker/build-push-action@v5
        with:
          context: ./Cafe_Management_System/menu-services
          push: true
          tags: zaimabbasi/cafe-menu-service:latest

      - name: build and push order-service
        uses: docker/build-push-action@v5
        with:
          context: ./Cafe_Management_System/order-services
          push: true
          tags: zaimabbasi/cafe-order-service:latest

      - name: build and push payment-service
        uses: docker/build-push-action@v5
        with:
          context: ./Cafe_Management_System/payment-services
          push: true
          tags: zaimabbasi/cafe-payment-service:latest

      - name: build and push inventory-service
        uses: docker/build-push-action@v5
        with:
          context: ./Cafe_Management_System/inventory-services
          push: true
          tags: zaimabbasi/cafe-inventory-service:latest

      - name: build and push customer-service
        uses: docker/build-push-action@v5
        with:
          context: ./Cafe_Management_System/customer-services
          push: true
          tags: zaimabbasi/cafe-customer-service:latest
